export const Screens = {
    login: 'login',
    categories:'categories',
    meals:'meals',
    mealDetail:'mealDetail'
}

export const Colors = {
    primary: '#096B68',
    accent: '#FFFBDE',
    secondary: '#90D1CA'
}


export const CATEGORIES = [
    { id: 'c1', title: 'Indian', color: '#FF6F61' },
    { id: 'c2', title: 'Chinese', color: '#FFD166' },
    { id: 'c3', title: 'Italian', color: '#06D6A0' },
    { id: 'c4', title: 'Mexican', color: '#EF476F' },
    { id: 'c5', title: 'Thai', color: '#118AB2' },
    { id: 'c6', title: 'Japanese', color: '#073B4C' },
    { id: 'c7', title: 'American', color: '#F4A261' },
    { id: 'c8', title: 'French', color: '#2A9D8F' },
    { id: 'c9', title: 'Mediterranean', color: '#E76F51' },
    { id: 'c10', title: 'Middle Eastern', color: '#8338EC' }
]


export const MEALS = [
  // Category c1: Indian
  {
    id: 'm1',
    categoryIds: ['c1'],
    title: 'Butter Chicken',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 45,
    ingredients: ['500g chicken', '2 tbsp butter', '1 cup tomato puree', '1/2 cup cream', 'Spices'],
    steps: ['Marinate chicken', 'Cook chicken', 'Make sauce', 'Combine', 'Simmer'],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    backgroundColor: '#f8b195'
  },
  {
    id: 'm2',
    categoryIds: ['c1'],
    title: 'Chole Bhature',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 50,
    ingredients: ['Chickpeas', 'Spices', 'Flour', 'Yogurt', 'Oil'],
    steps: ['Cook chickpeas', 'Make gravy', 'Knead dough', 'Fry', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    backgroundColor: '#f67280'
  },
  {
    id: 'm3',
    categoryIds: ['c1'],
    title: 'Palak Paneer',
    affordability: 'affordable',
    complexity: 'simple',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 30,
    ingredients: ['Spinach', 'Paneer', 'Spices', 'Cream', 'Garlic'],
    steps: ['Blanch spinach', 'Sauté garlic', 'Add paneer', 'Simmer', 'Serve'],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    backgroundColor: '#c06c84'
  },
  {
    id: 'm4',
    categoryIds: ['c1'],
    title: 'Biryani',
    affordability: 'pricey',
    complexity: 'hard',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 90,
    ingredients: ['Rice', 'Meat/veg', 'Spices', 'Yogurt', 'Onions'],
    steps: ['Marinate', 'Cook rice', 'Layer', 'Cook on low', 'Serve'],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    backgroundColor: '#6c5b7b'
  },
  {
    id: 'm5',
    categoryIds: ['c1'],
    title: 'Dosa',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 40,
    ingredients: ['Rice', 'Urad dal', 'Salt', 'Oil', 'Potato filling'],
    steps: ['Ferment batter', 'Cook dosa', 'Add filling', 'Fold', 'Serve'],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    backgroundColor: '#355c7d'
  },

  // Category c2: Chinese
  {
    id: 'm6',
    categoryIds: ['c2'],
    title: 'Kung Pao Chicken',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 30,
    ingredients: ['Chicken', 'Peanuts', 'Chili', 'Soy sauce', 'Bell peppers'],
    steps: ['Marinate', 'Stir-fry', 'Add sauce', 'Simmer', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    backgroundColor: '#99b898'
  },
  {
    id: 'm7',
    categoryIds: ['c2'],
    title: 'Sweet and Sour Pork',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 35,
    ingredients: ['Pork', 'Pineapple', 'Vinegar', 'Sugar', 'Peppers'],
    steps: ['Fry pork', 'Make sauce', 'Mix and cook', 'Simmer', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    backgroundColor: '#feceab'
  },
  {
    id: 'm8',
    categoryIds: ['c2'],
    title: 'Fried Rice',
    affordability: 'affordable',
    complexity: 'simple',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 25,
    ingredients: ['Rice', 'Veggies', 'Eggs', 'Soy sauce', 'Oil'],
    steps: ['Stir-fry veggies', 'Add rice', 'Add eggs', 'Season', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    backgroundColor: '#ff847c'
  },
  {
    id: 'm9',
    categoryIds: ['c2'],
    title: 'Spring Rolls',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 45,
    ingredients: ['Wrappers', 'Veggies', 'Oil', 'Soy sauce', 'Spices'],
    steps: ['Prepare filling', 'Roll', 'Fry', 'Serve'],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    backgroundColor: '#e84a5f'
  },
  {
    id: 'm10',
    categoryIds: ['c2'],
    title: 'Mapo Tofu',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://blog.swiggy.com/wp-content/uploads/2024/03/Puri-Aloo-1024x538.png',
    duration: 30,
    ingredients: ['Tofu', 'Pork', 'Bean paste', 'Garlic', 'Onion'],
    steps: ['Fry pork', 'Add tofu', 'Simmer', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    backgroundColor: '#2a363b'
  },

  // Category c3: Italian
  {
    id: 'm11',
    categoryIds: ['c3'],
    title: 'Margherita Pizza',
    affordability: 'pricey',
    complexity: 'medium',
    imageUrl: 'https://example.com/images/margherita.jpg',
    duration: 40,
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Basil'],
    steps: ['Roll dough', 'Add toppings', 'Bake', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    backgroundColor: '#f6cd61'
  },
  {
    id: 'm12',
    categoryIds: ['c3'],
    title: 'Spaghetti Carbonara',
    affordability: 'affordable',
    complexity: 'medium',
    imageUrl: 'https://example.com/images/carbonara.jpg',
    duration: 30,
    ingredients: ['Spaghetti', 'Eggs', 'Pecorino', 'Pancetta', 'Pepper'],
    steps: ['Cook pasta', 'Mix sauce', 'Combine', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    backgroundColor: '#ff6f69'
  },
  {
    id: 'm13',
    categoryIds: ['c3'],
    title: 'Lasagna',
    affordability: 'pricey',
    complexity: 'hard',
    imageUrl: 'https://example.com/images/lasagna.jpg',
    duration: 90,
    ingredients: ['Lasagna sheets', 'Meat', 'Tomato sauce', 'Bechamel', 'Cheese'],
    steps: ['Prepare layers', 'Assemble', 'Bake', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    backgroundColor: '#ffcc5c'
  },
  {
    id: 'm14',
    categoryIds: ['c3'],
    title: 'Risotto',
    affordability: 'pricey',
    complexity: 'medium',
    imageUrl: 'https://example.com/images/risotto.jpg',
    duration: 40,
    ingredients: ['Arborio rice', 'Onion', 'Stock', 'Parmesan'],
    steps: ['Sauté onion', 'Add rice and stock', 'Stir', 'Add cheese', 'Serve'],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    backgroundColor: '#88d8b0'
  },
  {
    id: 'm15',
    categoryIds: ['c3'],
    title: 'Pesto Pasta',
    affordability: 'affordable',
    complexity: 'simple',
    imageUrl: 'https://example.com/images/pesto_pasta.jpg',
    duration: 25,
    ingredients: ['Pasta', 'Pesto sauce', 'Parmesan'],
    steps: ['Boil pasta', 'Add pesto', 'Mix', 'Serve'],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    backgroundColor: '#96ceb4'
  },


];

